package uk.gov.pay.directdebit.events.model;

public enum GovUkPayEventType {
    MANDATE_CREATED,
    MANDATE_TOKEN_EXCHANGED,
    MANDATE_SUBMITTED_TO_PROVIDER,
    MANDATE_USER_SETUP_EXPIRED,
    MANDATE_CANCELLED_BY_USER,
    MANDATE_CANCELLED_BY_USER_NOT_ELIGIBLE,
    PAYMENT_SUBMITTED
}
