package uk.gov.pay.directdebit.events.model;

public enum GovUkPayEventType {
    MANDATE_CREATED,
    MANDATE_TOKEN_EXCHANGED,
    MANDATE_SUBMITTED_TO_PROVIDER,
    MANDATE_USER_SETUP_EXPIRED,
    MANDATE_USER_SETUP_CANCELLED,
    MANDATE_USER_SETUP_CANCELLED_NOT_ELIGIBLE,
    MANDATE_UNEXPECTED_ERROR,
    MANDATE_ERROR_SUBMITTING_TO_PROVIDER,
    PAYMENT_CREATED,
    PAYMENT_SUBMITTED,
    PAYMENT_ERROR_SUBMITTING_TO_PROVIDER
}
